### ISSUE TITLE
icons on menus

### ISSUE THREAD

**Issue by comonier** [kicjow/Crazy-Auctions#49]
![1](https://user-images.githubusercontent.com/19571541/47199440-0b91a300-d348-11e8-8b8e-cc7d2825f869.jpg)
![2](https://user-images.githubusercontent.com/19571541/47199441-0b91a300-d348-11e8-9146-21df3cd43fe2.jpg)

**Comment by comonier** [comment]
why i just can see the first options and not the second ?

**Comment by Colin13** [comment]
Crazy Auctions is not stable for 1.13.x use.
Can you provide further info on your issue so that I could possibly help you?

**Comment by comonier** [comment]
CrazyAuctions v1.2.6*
Paper version git-Paper-411 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Everything does not work perfectly. I just do not understand why the icons inside the auction menu do not appear as they should, instead they appear this block of sandstone.

**Comment by kicjow** [comment]
@comonier All those items are editable in the Config.yml. It is because 1.13 changed how items work and now you need to use the new 1.13 item names.
Only fix at the moment is to go into the Config.yml and change the Item IDs to the Item Names.
Item Names can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

**Comment by comonier** [comment]
I do not think that's the problem. Since in config.yml it is described:

CurrentItems: #The Book in the Current GUI items.
          Item: '340'

340 is the book id
if I type give comonier 340 1 the system gives me a book. he soon recognizes the book as 340. yet in the menu appears a red clay block
